# Custom Workflow for Rperform CI test
name: R

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  build_rperform:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rperform environment and run the sample code
        uses:  ./.github/actions/test-info